"""empty message

Revision ID: c801f29f8460
Revises: d02ee9a59f83
Create Date: 2025-08-12 06:22:04.157108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c801f29f8460'
down_revision = 'd02ee9a59f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
